# This is a basic workflow to help you get started with Actions

name: metrics.conholdate.com-live

# Controls when the action will run. 
on:
  workflow_dispatch:  
  # Scheduled trigger
  #schedule:
   # - cron: '59 */11 * * *'
  
    # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ live ]
    # paths:
    #   - 'content/aspose.com/**'
    #   - '!images/codeporting/**'
    #   - '!images/conholdate/**'

  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
            repository: conholdate-com-metrics/conholdate-com-metrics
            token: ${{ secrets.REPO_TOKEN }}
            ref: live
            submodules: true  # Fetch Hugo themes
            fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
                              #extended: true (Not being used on QA etc.)

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: '0.110.0'
            
      # Also specifies the theme we want to use
      - name: Build
        run: hugo --config "./config/conholdate-com-live.toml" --minify
        
      - name: Deploy metrics.conholdate.com
        run: hugo --config "./config/conholdate-com-live.toml" deploy --target "Production" --invalidateCDN --maxDeletes 256 #-force?
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}